# Generated by Django 2.0.2 on 2018-02-04 00:00

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('legCode', models.TextField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=25)),
                ('latitude', models.CharField(max_length=2)),
                ('longitude', models.CharField(max_length=2)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('EIN', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=300)),
                ('principal', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('organization_type', models.CharField(max_length=30)),
                ('business_type', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together={('zipcode', 'street')},
        ),
        migrations.AddField(
            model_name='legislation',
            name='maps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smu.Map'),
        ),
    ]
